title: CPT-363
default_lang: en
author:
  name: 'John Appleseed'
  email: john@email.com
taxonomies:
  - category
  - tag
metadata:
  description: 'A short description of your course would go here'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
displaymenuentries:
  enabled: false
menu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'http://getgrav.org/'
icon:
  post: calendar-o
gitrepo:
  editlinklocation: menu
  editlinkicon: github
  editlinktext: 'Edit this Page'
twittertimeline:
  enabled: false
  url: 'https://twitter.com/hibbittsdesign/lists/cpt-363'
  text: 'A Twitter List by @hibbittsdesign'
  height: 700
hidehomemenulink: false
cc_license:
  enabled: true
  type: ccby
