title: CPT-363
default_lang: en
author:
  name: 'Site Author'
  email: siteauthor@email.com
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'A short description of your course would go here'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
chromeless:
  enabled: false
gitrepo:
  editlinklocation: menu
  editthemelinklocation: none
  editthemelinktext: 'Site Theme Files'
  typeofgitsyncrepolink: edit
  editnotetext: 'Have a suggestion?'
displaymenuentries:
  enabled: false
menu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'http://getgrav.org/'
hidehomemenulink: true
hidesidebaronblogpages:
  enabled: false
twittertimeline:
  enabled: false
  url: 'https://twitter.com/hibbittsdesign/lists/cpt-363'
  text: 'A Twitter Lists by @hibbittsdesign'
  height: 700
cc_license:
  enabled: false
  type: ccby
  icon: false
hidesidebaronblog:
  enabled: '0'
chromelesspages:
  enabled: false
icon:
  post: calendar-o
