title: CPT-363
default_lang: en
author:
  name: 'John Appleseed'
  email: john@email.com
taxonomies:
  - category
  - tag
metadata:
  description: 'A short description of your course would go here'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
chromeless:
  enabled: '0'
gitrepo:
  editlinklocation: menu
  editnotetext: 'Have a suggestion?'
  editlinktext: 'Edit this Page'
  editlinkicon: github
  editthemelinklocation: none
  editthemelinktext: 'Site Theme Files'
displaymenuentries:
  enabled: false
menu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'http://getgrav.org/'
hidehomemenulink: false
icon:
  post: calendar-o
hidesidebaronblogpages:
  enabled: false
twittertimeline:
  enabled: false
  url: 'https://twitter.com/hibbittsdesign/lists/cpt-363'
  text: 'A Twitter List by @hibbittsdesign'
  height: 700
cc_license:
  enabled: false
  type: ccby
hidesidebaronblog:
  enabled: '0'
chromelesspages:
  enabled: false
