core:
  grav:
    version: 1.7.46
    history:
      version: 1.6.31
      date: '2020-12-20 16:57:04'
      0: { version: 1.7.0, date: '2021-01-20 18:04:05' }
      1: { version: 1.7.1, date: '2021-01-20 19:38:54' }
      2: { version: 1.7.14, date: '2021-05-05 14:26:28' }
      3: { version: 1.7.17, date: '2021-07-10 15:10:30' }
      4: { version: 1.7.22, date: '2021-09-25 21:13:36' }
      5: { version: 1.7.25, date: '2021-11-28 18:59:39' }
      6: { version: 1.7.34, date: '2022-07-06 19:29:31' }
      7: { version: 1.7.37.1, date: '2022-10-14 20:25:48' }
      8: { version: 1.7.39.4, date: '2023-03-06 21:22:06' }
      9: { version: 1.7.40, date: '2023-03-28 18:53:50' }
      10: { version: 1.7.41.1, date: '2023-05-18 21:27:01' }
      11: { version: 1.7.42.1, date: '2023-07-05 20:36:55' }
      12: { version: 1.7.43, date: '2023-10-03 17:16:54' }
      13: { version: 1.7.46, date: '2024-07-17 21:12:03' }
    schema: 1.7.0_2020-11-20_1
