@extends:
    '@parent'

form:
    fields:
        sectionone:
            type:                              section
            title:                             Chromeless Pages
            underline:                         true

            fields:
                chromeless.enabled:
                    type:                      toggle
                    label:                     Hide Global Navigation Elements on all Pages
                    description:               'When enabled, only page content will be displayed. This is often useful when embedding Course Hub pages within another system (e.g. an LMS such as Canvas using the <a href="https://www.eduappcenter.com/apps/63#.WUWhaRPysXo" target="_blank">Redirect Tool</a> LTI).'
                    highlight:                 1
                    default:                   0
                    options:
                        1:                     Yes
                        0:                     No
                    validate:
                        type:                  bool

        sectiontwo:
            type:                              section
            title:                             Git Sync Link
            underline:                         true

            fields:
                gitrepo.editlinklocation:
                    type: select
                    size: medium
                    label: Display of Git Sync Link
                    default: menu
                    options:
                        menu: Menu
                        page: Page (visible when 'Chromeless')
                        footer: Footer
                        none: None

                gitrepo.typeofgitsyncrepolink:
                    type: select
                    size: medium
                    label: Type of Git Sync Link
                    default: edit
                    options:
                        view: View Git Repository
                        edit: View/Edit Page in Git Repository

                gitrepo.editlinkicon:
                    type:                      text
                    size:                      small
                    label:                     Custom Git Sync Font Awesome Icon
                    description:               Short name, e.g. 'code-fork'.
                    help:                      Icon short name.
                    validate:
                        type:                  text

                gitrepo.editlinktext:
                  type:                        input.text
                  size:                        medium
                  label:                       Custom Git Sync Link Text
                  description:                 Git Sync link text, e.g. 'View Page in GitHub'.

                gitrepo.editnotetext:
                  type:                        input.text
                  size:                        long
                  label:                       Text before Git Sync Link on Pages
                  default:                     'Have a suggestion or correction?'
                  description:                 'The text before the Git Sync link (only when displayed on a Page).'

                gitrepo.edittreeurl:
                    type:                      text
                    size:                      long
                    label:                     Custom Git Repository Tree URL
                    help:                      Enter the URL that leads to the pages folder of your Git Repository.
                    description:               "URL path to the pages folder, but with '/pages' and everything following it removed. For example, 'https://github.com/paulhibbitts/demo-grav-course-hub/tree/master'."
                    validate:
                        type:                  URL

        sectionthree:
            type:                              section
            title:                             Edit Site Theme Files in Git Link
            underline:                         true

            fields:
                gitrepo.editthemelinklocation:
                    type:                      select
                    label:                     Display of Edit Site Theme Files Link
                    default:                   None
                    size:                      small
                    options:
                        'none':                None
                        'footer':              Footer

                gitrepo.editthemelinktext:
                  type:                        input.text
                  size:                        medium
                  label:                       Edit Site Theme Files Link Text
                  default:                     'Site Theme Files'
                  description:                 Customize the Edit Site Theme Files link text.

        sectionfour:
            type:                              section
            title:                             Menubar
            underline:                         true

            fields:
                displaymenuentries.enabled:
                    type:                      toggle
                    label:                     Display Custom Menubar Items
                    help:                      Determines if any defined custom menubar entries are displayed in the menubar.
                    default:                   0
                    highlight:                 1
                    options:
                        1:                     Yes
                        0:                     No
                    validate:
                        type:                  bool

                menu:
                    name:                      menu
                    type:                      list
                    label:                     Custom Menubar Items
                    fields:
                      .text:
                        type:                  text
                        label:                 Text
                      .icon:
                        type:                  text
                        label:                 Icon
                      .url:
                        type:                  text
                        label:                 URL

                hidehomemenulink:
                    type:                      toggle
                    label:                     Include Homepage Link in Menubar
                    help:                      Determines if the link to the Homepage is included in the menubar.
                    default:                   0
                    highlight:                 0
                    options:
                        0:                     Yes
                        1:                     No
                    validate:
                        type:                  bool

        sectionfive:
            type:                              section
            title:                             Blog Posts
            underline:                         true

            fields:
                icon.post:
                    type:                      text
                    size:                      small
                    label:                     Default Blog Post Font Awesome Icon
                    default:                   'calendar-o'
                    description:               Short name, e.g. 'calendar-o'.
                    help:                      Determines the default Font Awesome icon used for the blog posts.
                    validate:
                        type:                  text

        sectionsix:
            type:                              section
            title:                             Sidebar
            underline:                         true

            fields:

                hidesidebaronblogpages.enabled:
                    type:                      toggle
                    label:                     Display Sidebar on Blog Pages
                    highlight:                 0
                    default:                   0
                    options:
                        0:                     Yes
                        1:                     No
                    validate:
                        type:                  bool

                twittertimeline.enabled:
                    type:                      toggle
                    label:                     Display Twitter Widget in Sidebar
                    highlight:                 1
                    default:                   0
                    options:
                        1:                     Yes
                        0:                     No
                    validate:
                        type:                  bool

                twittertimeline.url:
                    type:                      text
                    size:                      large
                    label:                     Twitter Widget URL
                    help:                      Enter the URL for your embedable Twitter Widget.
                    validate:
                        type:                  URL

                twittertimeline.text:
                    type:                      text
                    size:                      large
                    label:                     Twitter Widget Text
                    validate:
                        type:                  text

                twittertimeline.height:
                    type:                      text
                    size:                      small
                    label:                     Twitter Widget Height (px)
                    default:                   600
                    validate:
                        type:                  int
                        min:                   100
                        max:                   1000

        sectionseven:
            type:                              section
            title:                             Creative Commons (CC) License
            underline:                         true

            fields:
                cc_license.enabled:
                    type:                      toggle
                    label:                     Display CC License
                    highlight:                 1
                    default:                   0
                    options:
                        1:                     Yes
                        0:                     No
                    validate:
                        type:                  bool

                cc_license.type:
                  type:                        select
                  label:                       CC License Type
                  default:                     ccby
                  size:                        long
                  description:                 'Looking for more info about Creative Commons (CC) Licenses?<br> Visit the <a href="https://creativecommons.org/" target="_blank">creativecommons.org</a> site.'
                  options:
                      ccby:                    'CC Attribution'
                      ccbysa:                  'CC Attribution Share Alike'
                      ccbynd:                  'CC Attribution No Derivatives'
                      ccbync:                  'CC Attribution Non-Commercial'
                      ccbyncsa:                'CC Attribution Non-Commercial Share Alike'
                      ccbyncnd:                'CC Attribution Non-Commercial No Derivatives'

                cc_license.text:
                    type:                      text
                    size:                      long
                    description:               'For example, ''Except where otherwise noted.'''
                    label:                     CC License Text
                    validate:
                        type:                  text
